[package]
name = "coloring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.5"
pest_derive = "2.7.5"
pest_consume = "1.1.3"

[lib]
name = "coloring"
path = "src/lib.rs"